# Generated by Django 3.0.3 on 2020-02-17 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20200217_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 8, 34, 49, 977538, tzinfo=utc)),
        ),
    ]
