# Generated by Django 2.2.5 on 2019-12-03 15:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20191202_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 15, 42, 6, 567214, tzinfo=utc)),
        ),
    ]
